using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Serialization;

namespace Entity
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //     运行时版本:4.0.30319.1
    //
    //     对此文件的更改可能会导致不正确的行为，并且如果
    //     重新生成代码，这些更改将会丢失。
    // </auto-generated>
    //------------------------------------------------------------------------------



    // 
    // 此源代码由 xsd 自动生成, Version=4.0.30319.1。
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class AreaJson
    {

        private string _code="-1";
        private Bodydata _data;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Bodydata data
        {
            get
            {
                return this._data;
            }
            set
            {
                this._data = value;
            }
        }




        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class Bodydata
        {

            private string _country;
            private string _country_id;
            private string _area;
            private string _area_id;
            private string _region;
            private string _region_id;
            private string _city;
            private string _city_id;
            private string _county;
            private string _county_id;
            private string _isp;
            private string _isp_id;
            private string _ip;


            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string country
            {
                get
                {
                    return this._country;
                }
                set
                {
                    this._country = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string country_id
            {
                get
                {
                    return this._country_id;
                }
                set
                {
                    this._country_id = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string area
            {
                get
                {
                    return this._area;
                }
                set
                {
                    this._area = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string area_id
            {
                get
                {
                    return this._area_id;
                }
                set
                {
                    this._area_id = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string region
            {
                get
                {
                    return this._region;
                }
                set
                {
                    this._region = value;
                }
            }


            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string region_id
            {
                get
                {
                    return this._region_id;
                }
                set
                {
                    this._region_id = value;
                }
            }


            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string city
            {
                get
                {
                    return this._city;
                }
                set
                {
                    this._city = value;
                }
            }


            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string city_id
            {
                get
                {
                    return this._city_id;
                }
                set
                {
                    this._city_id = value;
                }
            }


            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string county
            {
                get
                {
                    return this._county;
                }
                set
                {
                    this._county = value;
                }
            }


            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string county_id
            {
                get
                {
                    return this._county_id;
                }
                set
                {
                    this._county_id = value;
                }
            }


            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string isp
            {
                get
                {
                    return this._isp;
                }
                set
                {
                    this._isp = value;
                }
            }


            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string isp_id
            {
                get
                {
                    return this._isp_id;
                }
                set
                {
                    this._isp_id = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string  ip
            {
                get
                {
                    return this._ip;
                }
                set
                {
                    this._ip = value;
                }
            }
        }
     
     
     

    }
}